apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: daskclusters.dask-gateway-eks.github.com
  creationTimestamp: null
spec:
  group: dask-gateway-eks.github.com
  names:
    kind: DaskCluster
    listKind: DaskClusterList
    plural: daskclusters
    singular: daskcluster
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        # NOTE: While we define a schema, it is a dummy schema that doesn't
        #       validate anything. We just have it to comply with the schema of
        #       a CustomResourceDefinition that requires it.
        #
        #       A decision has been made to not implement an actual schema at
        #       this point in time due to the additional maintenance work it
        #       would require.
        #
        #       Reference: https://github.com/dask/dask-gateway/issues/434
        #
        openAPIV3Schema:
          x-kubernetes-preserve-unknown-fields: true
          required:
            - spec
          type: object
          properties:
            status:
              type: object
              properties:
                authSecretName:
                  type: string
                clusterState:
                  type: string
                clusterCreationState:
                  type: string
                observedGeneration:
                  type: integer
---

apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: cluster-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: dask-gateway-eks.github.com/v1alpha1
    resource: daskclusters
  childResources:
  - apiVersion: v1
    resource: pods
  - apiVersion: v1
    resource: services
  - apiVersion: v1
    resource: secrets
  - apiVersion: traefik.containo.us/v1alpha1
    resource: ingressroutetcps
  - apiVersion: traefik.containo.us/v1alpha1
    resource: ingressroutes
  - apiVersion: traefik.containo.us/v1alpha1
    resource: tlsoptions
  hooks:
    sync:
      webhook:
        url: http://host.docker.internal:8000/sync
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: common-dask-middleware
spec:
  chain:
    middlewares:
      - name: redirect-dask-dashboard
      - name: compress-dask-dashboard
      - name: strip-dask-prefix
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-dask-prefix
spec:
  stripPrefixRegex:
    regex:
      # Should only be added when running locally
      - "/gateway-api/[a-z0-9]+/"
      - "/dashboard/[a-z0-9]+/"
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: compress-dask-dashboard
spec:
  compress: {}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-dask-dashboard
spec:
  redirectRegex:
    regex: ^(.*/dashboard/[a-z0-9]+)/$
    replacement: ${1}/status
