POST http://127.0.0.1:8000/api/v1/clusters/
accept: application/json
Content-Type: application/json

{
  "image": "daskgateway/dask-gateway:0.9.0",
  "min_workers": 0,
  "max_workers": 0,
  "environment": {
    "additionalProp1": "string",
    "additionalProp2": "string",
    "additionalProp3": "string"
  },
  "worker_resources": {
    "memory": 0,
    "cores": 0,
    "gpus": 0
  },
  "scheduler_resources": {
    "memory": 0,
    "cores": 0,
    "gpus": 0
  }
}

> {%
    client.global.set("cluster_id", response.body);
%}

###

POST http://127.0.0.1:8000/api/v1/clusters/{{cluster_id}}/adapt
accept: application/json
Content-Type: application/json

{
  "minimum": 0,
  "maximum": 15,
  "active": true
}

###

POST http://127.0.0.1:8000/api/v1/clusters/{{cluster_id}}/adapt
accept: application/json
Content-Type: application/json

{
  "minimum": 3,
  "maximum": 100,
  "active": true
}

###

POST http://127.0.0.1:8000/api/v1/clusters/{{cluster_id}}/adapt
accept: application/json
Content-Type: application/json

{
  "minimum": 5,
  "maximum": 100,
  "active": true
}

###

POST http://127.0.0.1:8000/api/v1/clusters/{{cluster_id}}/adapt
accept: application/json
Content-Type: application/json

{
  "minimum": 60,
  "maximum": 100,
  "active": true
}

###

POST http://127.0.0.1:8000/api/v1/clusters/{{cluster_id}}/adapt
accept: application/json
Content-Type: application/json

{
  "minimum": 1,
  "maximum": 100,
  "active": true
}
